# Generated by Django 4.1.7 on 2023-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_remove_article_pub_date_remove_article_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('IT', 'IT News'), ('HL', 'Health'), ('RS', 'Rest')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
